# Generated by Django 4.2.1 on 2023-06-21 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0007_alter_dislike_unique_together_remove_dislike_song_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='dislike_to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='music_api.song'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='user_that_disliked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='music_api.song'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_that_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
