version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./static:/app/static

  frontend:
    build:
      context: ./frontend   # Set the context to the frontend app directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=toni
      - POSTGRES_PASSWORD=toni1234
      - POSTGRES_DB=music_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
