# Generated by Django 4.2.1 on 2023-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
