# Generated by Django 4.2.1 on 2023-06-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0006_song_is_favourite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='song',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='song',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
