# Generated by Django 4.2.1 on 2023-06-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0002_alter_userprofile_age_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
