# Generated by Django 4.2.1 on 2023-06-23 17:37

from django.db import migrations, models
import music_backend_apis.accounts_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=12, validators=[music_backend_apis.accounts_api.validators.validate_age_range]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[music_backend_apis.accounts_api.validators.validate_bio_length]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[music_backend_apis.accounts_api.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[music_backend_apis.accounts_api.validators.validate_name_characters]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, validators=[music_backend_apis.accounts_api.validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=50, validators=[music_backend_apis.accounts_api.validators.validate_username]),
        ),
    ]
